import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Select Page
        </h1>
        <h1 className={styles.nextaction}>
          <Link href="/inputRecordPage">Input Record Page</Link>
        </h1>
        <h1 className={styles.nextaction}>
          <Link href="/searchRecordPage">Records List Page</Link>
        </h1>
        <h1 className={styles.nextaction}>
          <Link href="/chartPage">Line Chart</Link>
        </h1>
        <h1 className={styles.nextaction}>
          <Link href="/resumePage">PDF(Coding...)</Link>
        </h1>

        <p className={styles.description}>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>
        </div>
      </main>
    </div>
  )
}
